name: Flask App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Basic syntax check
        run: |
          python -m py_compile home.py

      - name: Run Flask App (optional - for debug only)
        run: |
          echo "Flask app ready. You can now deploy or run tests."
